[build]
builder = "NIXPACKS"

[deploy]
startCommand = "NODE_ENV=production node dist/boot.js"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[environments]
production = { numReplicas = 1 }
